IF
    True()
THEN
    RESPONSE #100
        CutSceneId(Player1)
        ScreenShake([30.30],5)
        MoveViewPoint([742.482],100)
        CreateVisualEffect("SPSUMGTE",[742.482])
        Wait(2)
        CreateVisualEffect("SPFIREPI",[742.482])
        Wait(2)
        CreateCreature("OHDAZOTH",[742.482],SSW)  // Azothet
        Wait(3)
        EndCutSceneMode()
        ActionOverride("bfdorn",StartDialogueNoSet(Player1))
END

